name: linting

on: 
     push:
        branches:
            - main

jobs:
    codeCheckout_linting:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: http://github.com/actions/checkout@v5
            
              - name: linting
                uses: 
        

